In [232]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [233]:
file_path = "Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv"
df = pd.read_csv(file_path)

In [234]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [235]:
tf.__version__  # tensorflow version 2

'2.3.0'

# Preprocessing

Baiscally, 
- define the training data set (X)
- define the lable data (y)
- encoding categorial data
- split traing and testing 
- feature scaling

## Get X and y

In [236]:
# from here we will work with numpy array for training

# get columns by index - from 3 and excludes the last one which is for lable
X = df.iloc[:, 3:-1].values  # .values to convert to numpy arr


In [237]:
y = df.iloc[:, -1].values  # y label using last column "Exited"


In [238]:
print(X)  # looks like list

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Encoding categorical data

In [239]:
# encode categorical data to numeric
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# encode the gender column, here we are just overriding the X var
X[:,2] = le.fit_transform(X[:,2])

In [240]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [241]:
# "One Hot Encoding" the country column
# this is similar to sklearn.get_dummies in that we are transforming the categorial data into binary
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# columntrasformer gives you ability to customize the transformation - e.g, you can apply OneHotEncoder to the cloumn
# here column index 1 is the country column
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [242]:
# OneHotEncoding moves the transformed columns to the beginning
# for example, "France" is now represented as 1, 0, 0
print(X)
X[0]  

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

## Split Training and Testing

In [243]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature scaling

In [244]:
# It is very important to standardize scaling in Neuro Network
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
# apply feature scaling to all the features
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [245]:
X_train  # all the features have been standardized

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Modeling

## Initialize ANN model

In [246]:
ann = tf.keras.models.Sequential()  # sequential class is the most basic ANN model


## Add input layer and first hidden layer

In [247]:
# add first hidden layer 
# add nerons, you need to try differnt and find a good num yourself
# relu is the rectifier activation functions, refer to all different activation functions in previous tutorial
dense = tf.keras.layers.Dense(units=6, activation='relu')  
ann.add(dense) # add layers


## Add second hidden layer

In [248]:
# add second hidden layer
dense_2 = tf.keras.layers.Dense(units=6, activation='relu')  
ann.add(dense_2) # add another layers

## Add output layer

In [249]:
# use sigmoid activation function so you will also get probability of the prediction
# units set to 1
output_layer = tf.keras.layers.Dense(units=1, activation='sigmoid')  
ann.add(output_layer) # add another layers

## Training the ANN

In [250]:
# compile the ANN
# choose an optimizer 


# choose loss function - for binary classification use 'binary_crossentropy', for multi-calssification use 'categorical_crossentropy'
# metrics - choose metrics to evaluate your model
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [251]:
# train the model use the batch learning - compare result in batch
# epochs = neuro network has certain amount of epochs for training 
ann.fit(X_train, y_train, batch_size=32, epochs=100 )

# you can see the accuracy going up!!

Epoch 1/100
250/250 [==============================] - 0s 680us/step - loss: 0.5377 - accuracy: 0.7946
Epoch 2/100
250/250 [==============================] - 0s 576us/step - loss: 0.4662 - accuracy: 0.7930
Epoch 3/100
250/250 [==============================] - 0s 511us/step - loss: 0.4435 - accuracy: 0.7955
Epoch 4/100
250/250 [==============================] - 0s 521us/step - loss: 0.4371 - accuracy: 0.7987
Epoch 5/100
250/250 [==============================] - 0s 515us/step - loss: 0.4335 - accuracy: 0.7996
Epoch 6/100
250/250 [==============================] - 0s 559us/step - loss: 0.4307 - accuracy: 0.8023
Epoch 7/100
250/250 [==============================] - 0s 516us/step - loss: 0.4279 - accuracy: 0.8036
Epoch 8/100
250/250 [==============================] - 0s 550us/step - loss: 0.4260 - accuracy: 0.8066
Epoch 9/100
250/250 [==============================] - 0s 506us/step - loss: 0.4238 - accuracy: 0.8077
Epoch 10/100
250/250 [==============================] - 0s 508us/step - l

## Make prediction

In [252]:
# predict targt needs to be 2-d arry
record = [[
    1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000
]]

# make sure to apply the same scaling
# !! do not use fit_tranform !! 
# use transform method
scaled_record = sc.transform(record)

# now predict
ann.predict(scaled_record)  # you will get back probability

# if the result is greater than 0.5 then we can consider the customer will be exited

array([[0.01748216]], dtype=float32)

## Predict Test results

In [253]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))



[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Make confusion matrix

In [254]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1539   56]
 [ 217  188]]


0.8635

In [1]:
import numpy as np

In [19]:
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.expand_dims(arr, axis=1)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [27]:
np.expand_dims(arr, axis=1)[2]

array([[7, 8, 9]])